version: "3"

services:
  rstudio:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    image: nujabec/myrocker:20250917
    env_file: ./docker/.env
    ports:
      - "50003:8787"
    volumes:
      - ../srv/:/home/rstudio/srv/
      - samba-mpd:/home/rstudio/mpd/
    environment:
      PASSWORD: rs
      ROOT: "TRUE"
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    restart: always

volumes:
  samba-mpd:
    driver_opts:
      type: cifs
      o: username=mpd,password=mpd,domain=WORKGROUP,rw,uid=1000,gid=1000,file_mode=0777,dir_mode=0777
      device: //200.200.17.40/mpd
